fix: pin the pip-tools version to 6.6.2
The pip-tools version currently used breaks with the error
"ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars'"
during the deployment. This is fixed in the version 6.6.2 as reported
in https://github.com/jazzband/pip-tools/issues/1617.

So, this commit pins the pip-tools version to 6.6.2